import type { ShopItem } from './shop-item.js';

/** Deterministic sample catalog for stories / tests (no network). */
export const SAMPLE_ITEMS: ShopItem[] = [
  {
    id: 'i1',
    name: 'Wizard hat',
    slot: 'HAT',
    rarity: 'EPIC',
    spriteAssetId: 'emoji:🎩',
    costCoins: 450,
    requiredLevel: 8,
  },
  {
    id: 'i2',
    name: 'Cap',
    slot: 'HAT',
    rarity: 'COMMON',
    spriteAssetId: 'emoji:🧢',
    costCoins: 60,
    owned: true,
    equipped: true,
  },
  {
    id: 'i3',
    name: 'Golden shades',
    slot: 'GLASSES',
    rarity: 'LEGENDARY',
    spriteAssetId: 'emoji:🕶️',
    costCoins: 1200,
    isPremiumOnly: true,
  },
  {
    id: 'i4',
    name: 'Hoodie',
    slot: 'TOP',
    rarity: 'UNCOMMON',
    spriteAssetId: 'emoji:🧥',
    costCoins: 180,
    owned: true,
  },
  {
    id: 'i5',
    name: 'Tee',
    slot: 'TOP',
    rarity: 'COMMON',
    spriteAssetId: 'emoji:👕',
    costCoins: 40,
    owned: true,
    equipped: true,
  },
  {
    id: 'i6',
    name: 'Jeans',
    slot: 'BOTTOM',
    rarity: 'COMMON',
    spriteAssetId: 'emoji:👖',
    costCoins: 50,
    owned: true,
    equipped: true,
  },
  {
    id: 'i7',
    name: 'Sneakers',
    slot: 'SHOES',
    rarity: 'RARE',
    spriteAssetId: 'emoji:👟',
    costCoins: 320,
  },
  {
    id: 'i8',
    name: 'Backpack',
    slot: 'ACCESSORY',
    rarity: 'UNCOMMON',
    spriteAssetId: 'emoji:🎒',
    costCoins: 150,
  },
  {
    id: 'i9',
    name: 'Robo pup',
    slot: 'PET',
    rarity: 'EPIC',
    spriteAssetId: 'emoji:🐶',
    costCoins: 900,
    requiredLevel: 15,
  },
  {
    id: 'i10',
    name: 'Sunset',
    slot: 'BACKGROUND',
    rarity: 'RARE',
    spriteAssetId: 'color:#fde68a',
    costCoins: 260,
    owned: true,
  },
  {
    id: 'i11',
    name: 'Violet frame',
    slot: 'FRAME',
    rarity: 'RARE',
    spriteAssetId: 'color:#7c4dff',
    costCoins: 300,
  },
  {
    id: 'i12',
    name: 'Party popper',
    slot: 'EMOTE',
    rarity: 'COMMON',
    spriteAssetId: 'emoji:🎉',
    costCoins: 30,
  },
];
